version: '3.9'
services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=permify
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  permify:
    image: ghcr.io/permify/permify:latest
    restart: always
    ports:
      - "3476:3476"
      - "3478:3478"
    volumes:
      - ./config.yaml:/config/config.yaml
    command: serve --config /config/config.yaml
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3476/healthz"]
      interval: 10s
      retries: 10
      start_period: 60s

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=adminpassword
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      database:
        condition: service_healthy

volumes:
  pg-data:
  pgadmin-data:
